"""migrating after editing trainers and pokemon

Revision ID: 307e5d41f1d8
Revises: 349a412a486d
Create Date: 2023-09-27 17:00:26.920374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307e5d41f1d8'
down_revision = '349a412a486d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_species', sa.String(), nullable=False),
    sa.Column('caught', sa.String(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pc_user', sa.String(), nullable=False))
        batch_op.drop_constraint('trainers_pc_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['pc_user'])
        batch_op.drop_column('pc_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pc_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('trainers_pc_name_key', ['pc_name'])
        batch_op.drop_column('pc_user')

    op.drop_table('pokemon')
    # ### end Alembic commands ###
