"""trying to add registered trainer table

Revision ID: 3eaf86fb9212
Revises: 307e5d41f1d8
Create Date: 2023-09-27 17:33:38.674178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eaf86fb9212'
down_revision = '307e5d41f1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registering_trainers',
    sa.Column('registering_id', sa.Integer(), nullable=True),
    sa.Column('registered_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registered_id'], ['trainers.id'], ),
    sa.ForeignKeyConstraint(['registering_id'], ['trainers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registering_trainers')
    # ### end Alembic commands ###
